const userData = {
  githubUsername: "harshmuriki",
  name: "Harsh Muriki",
  designation: "Student",
  avatarUrl: "/avatar.png",
  email: "harshsuhith@gmail.com",
  // phone: "+1 000 000 0000",
  address: "Atlanta, Georgia, USA.",
  projects: [
    {
      title: "RoboticGuitar",
      link: "",
      imgUrl: "/roboticguitar.jpg",
      tools: ["Python, Arduino, Raspberry Pi"],
      description: "A robotic guitar that plays music using a robotic arm and a guitar.",
      siteLink: "roboticguitar",
    },
    {
      title: "EvoCal",
      link: "https://evocal.vercel.app/",
      imgUrl: "/evocal.jpeg",
      tools: ["React, Node.js, Express, MongoDB"],
      description: "A web app to integrate Outlook/Gmail with Google Calendar.",
      siteLink: "evocal",
    },
    {
      title: "ResumeGPT",
      link: "https://github.com/harshmuriki",
      imgUrl: "/resumeGPT.jpeg",
      tools: ["Python, OpenAI, Streamlit"],
      description: "A GPT-3 based resume editor.",
      siteLink: "resumegpt",
    },
    {
      title: "SpotifyYoutube",
      link: "https://spotifyyoutube.vercel.app/",
      imgUrl: "/SpotifyYoutube.jpeg",
      tools: ["React, Node.js, Express, MongoDB"],
      description: "A web app to play Spotify songs on Youtube.",
      siteLink: "spotifyyoutube",
    },
    {
      title: "appie-AI-Chatbot",
      link: "https://github.com/harshmuriki/appie-AI-ChatBot",
      imgUrl: "/chatbot.jpeg",
      tools: ["Python, OpenAI, Streamlit"],
      description: "A chatbot that uses GPT-3.5 to chat with appian's customers.",
      siteLink: "appie-ai-chatbot",
    },
    {
      title: "Image2Plate",
      link: "https://image2plate.streamlit.app/",
      imgUrl: "/image2plate.jpeg",
      tools: ["Python, Streamlit"],
      description: "A web app to convert images to recipes.",
      siteLink: "image2plate",
    },
    {
      title: "Personal Portfolio",
      link: "https://harshmuriki-website.vercel.app/",
      imgUrl: "/portfolio.png",
      tools: ["React, Node.js, Express, MongoDB"],
      description: "My personal portfolio website.",
      siteLink: "personal-portfolio",
    },
    {
      title: "MemoryGPT",
      link: "https://github.com/harshmuriki/GPT-4-Based-Memory-Game",
      imgUrl: "/memorygame.jpeg",
      tools: ["Python, OpenAI, Streamlit"],
      description: "A memory game that uses GPT-4 to generate cards or colors.",
      siteLink: "gpt-4-based-memory-game",
    },
    {
      title: "MealPirates",
      link: "https://mealpirates.app/",
      imgUrl: "/mealpirates.jpeg",
      tools: ["React, Node.js, Express, MongoDB"],
      description: "A startup to deliver restaurant quality food at restaurant prices.",
      siteLink: "mealpirates",
    },
    {
      title: "Phone Pose",
      link: "https://github.com/harshmuriki/Find_Center_Phone_CV",
      imgUrl: "/phonecenter.jpeg",
      tools: ["Python, OpenCV, Streamlit"],
      description: "A computer vision project to find the center of a phone.",
      siteLink: "cv-finding-center-of-phone",
    },
  ],
  about: {
    title:
      "I'm a current senior at Georgia Tech majoring in Computer Science. I like to build software products in the fields of Robotics, Computer Vision, ML and AI.",
    description: [
      `I started coding directly with C++ in 6th Grade (which wasn't a great idea ;) ). Since then I have learnt (self-taught or courses or Chat-GPT-ing) languages like Python, JavaScript, React, Node.js, C++, C, Assembly (I go all the way).`,
      `I have got into this field when I wanted to break open my RC car that was given to me on my birthday just to see what was inside of it. Ever since then, I have been building and breaking (both physical and code) things.`,
      `I have since built projects like an AI chatbot, a GPT-4 based memory game, a GPT-3 based resume generator, a Spotify-Youtube music player, a startup to deliver restaurant quality food at restaurant prices, an AI/CV website to convert images to recipes, a computer vision project to find the center of a phone, and a website to showcase all my projects.`
    ],
    currentProject: "ResumeGPT",
    currentProjectUrl: "https://github.com/harshmuriki/resumeGPT",
  },
  experience: [
    {
      title: "Software Engineer Intern",
      company: "Appian",
      year: "2023",
      companyLink: "https://appian.com",
      desc: "Developed robust API request mocking product leveraging Kubernetes for enhanced resource efficiency and scalability",
      detail_desc: ["abcd", "efgh", "ijkl"],
      siteLink: "appian",
      photos: ["/appian1.png", "/appian2.png", "/appian3.png"],
      tools: ["Python, Kubernetes, Docker, React, Node.js, Express, MongoDB"],
    },
    {
      title: "Undergraduate Student Researcher",
      company: "Georgia Tech",
      year: "2021-2023",
      companyLink: "https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=10161045",
      desc: "Designed and constructed an autonomous robotic system that captures multiple 2D plant images, transforming them into 3D reconstructions for comprehensive volumetric analysis.",
      detail_desc: ["abcd", "efgh", "ijkl"],
      siteLink: "research",
      photos: ["/research1.png", "/research2.png", "/research3.png"],
      tools: ["Python, OpenCV, Streamlit"],
    },
    {
      title: "Co-Founder",
      company: "MealPirates",
      year: "2022-2023",
      companyLink: "https://mealpirates.app/",
      desc: "Developed a service which delivers resturant quality food at resturant prices.",
      detail_desc: ["abcd", "efgh", "ijkl"],
      siteLink: "mealpirates",
      photos: ["/mealpirates.png", "/mealpirates.png", "/mealpirates.png"],
      tools: ["React, Node.js, Express, MongoDB"],
    },
    {
      title: "Software Developer Intern",
      company: "Campus Talk",
      year: "2020-2021",
      companyLink: "https://harshmuriki.com/",
      desc: "Managed QA for iOS and Android apps, conducted competitive analysis, and oversaw the development and launch of new connectivity features.",
      detail_desc: ["abcd", "efgh", "ijkl"],
      siteLink: "campustalk",
      photos: ["/campustalk1.png", "/campustalk2.png", "/campustalk3.png"],
      tools: ["React, Node.js, Express, MongoDB"],
    },
    {
      title: "Robotics Intern",
      company: "Marut Drones",
      year: "2020",
      companyLink: "https://marutdrones.com/",
      desc: "Helped build an industrial drone.",
      detail_desc: ["abcd", "efgh", "ijkl"],
      siteLink: "marutdrones",
      photos: ["/marutdrones1.png", "/marutdrones2.png", "/marutdrones3.png"],
      tools: ["Python, Arduino, Raspberry Pi"],
    },
  ],
  resumeUrl:
    "https://drive.google.com/file/d/1jtAltpeey_kKf85OaCortyNs1Qu6VzQp/view?usp=sharing",
  socialLinks: {
    instagram: "https://www.instagram.com/harshmuriki24/",
    twitter: "https://twitter.com/Harshmuriki24",
    linkedin: "https://www.linkedin.com/in/venkata-harsh-muriki/",
    github: "https://github.com/harshmuriki",
    peerlist: "https://peerlist.io/harshmuriki",
    playbook: "https://www.playbook.com/s/blurredreality/QN1CshVfAwyQfCiMg1CyfMju"
  },
};

export default userData;
